#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_account="$1"; shift

  local attempts=1
  while true; do
    local session="$(pass "1password-${nm_account}-session" 2>/dev/null)"

    if [[ -z "$session" ]]; then
      pass "1password-${nm_account}" | op signin "${nm_account}" --output=raw | pass add -m "1password-${nm_account}-session" 1>/dev/null 2>&1
    fi

    export "OP_SESSION_${nm_account}"="$(pass "1password-${nm_account}-session" 2>/dev/null)"

    if op get vault "meh-$$" 2>&1 | grep -i "vault meh-$$ not found" >/dev/null 2>&1; then
      pass rm -f "1password-${nm_account}-session" 1>/dev/null 2>&1 || true
      break
    fi

    attempts="$((attempts + 1))"
    if [[ "$attempts" -gt 2 ]]; then
      echo "ERROR: unable to get a valid 1Password session" 1>&2
      exit 2
    fi
  done
  
  if [[ "$#" == 0 ]]; then
    exec "$SHELL"
  else
    exec "$@"
  fi
}

source sub "$BASH_SOURCE" "$@"
