#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_title="$1"; shift

  head -1 | sed 's#^#"#; s#$#"#' | op create item login "$( (jq '[{fields: [{k: "concealed", n: "TOTP_", t: "", v: .}], title: "totp"}]'; op get template Login) | jq -s '.[1].sections = .[0] | .[1]' | op encode)" --title="$nm_title"
  op totp "$@" "$nm_title"
}

source sub "$BASH_SOURCE" "$@"
