#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_title="$1"; shift

  op get totp "$nm_title"
}

source sub "$BASH_SOURCE" "$@"
