#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_op="$(op --version 2>/dev/null || true)"
  jq -n --arg op "$ver_op" '{op: $op}'
}

version "$@"
